name = "round-morning-0e82"
main = "oref-proxy.js"
compatibility_date = "2026-03-03"
preview_urls = false                                                                                                                                       

[placement]
mode = "smart"
location_hint = "me"
                                                                                                                                                                              
[observability]
enabled = true

[observability.logs]
enabled = true